apiVersion: v1
kind: Service
metadata:
  name : vprocache01 # make sure the same name service in app.props
spec:
  ports:
     - port: 11211 # accepte the request in this port
       targetPort : memcached-port #same name for deployment file
       protocol: TCP
  selector:
    app : vpromc # should give it a label : same name label in the deployment file
  type: ClusterIP  