apiVersion: v1
kind: Service
metadata:
  name : tomcat-for-java-app 
spec:
  ports:
     - port: 80 # accepte the request in this port
       targetPort : tomcat-port #same name for deployment file
       protocol: TCP
  selector:
    app : tomcat-for-java-app  # should give it a label : same name label in the deployment file
  type: LoadBalancer #elastic load balancer